[package]
name = "_"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version="0.2.7",features=["wasm-bindgen","js"]}
twox-hash = "1.6.3"
wasm-bindgen = "0.2.82"

[profile.release]
lto = true

